package test

import org.scalatest.Spec

sealed class ExceptionTest extends Spec {
  
  object `demo usage` {
    
    def safeDivide(x: Int,y: Int) = {
      try{
        Some(x/y)
      } catch {
        case _: ArithmeticException => None
      }// case
    }// safeDivide
    
    def `demo catch` = {
      assertResult(2)(safeDivide(5, 2).get)
      assert(safeDivide(6, 0).isEmpty)
    }
    
  }

}